---
services:

  redis:
    image: redis:alpine
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_DB=moodle
    volumes:
      - postgres:/var/lib/postgresql

  moodle:
    #image: erseco/alpine-moodle
    build:
      context: .
      args:
        # To use a specific Moodle version, set MOODLE_VERSION to git release tag.
        # You can find the list of available tags at:
        # https://api.github.com/repos/moodle/moodle/tags
        #
        # Example:
        # MOODLE_VERSION: v4.5.3
        # MOODLE_VERSION: v5.0.1
        MOODLE_BRANCH: MOODLE_502_STABLE
    restart: unless-stopped
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      SITE_URL: http://localhost
      DB_TYPE: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: moodle
      DB_PREFIX: mdl_
      REDIS_HOST: redis
      REVERSEPROXY: false
      SSLPROXY: false
      MOODLE_EMAIL: user@example.com
      MOODLE_LANGUAGE: en
      MOODLE_SITENAME: New-Site
      MOODLE_USERNAME: moodleuser
      MOODLE_PASSWORD: PLEASE_CHANGEME
      MOODLE_MAIL_NOREPLY_ADDRESS: noreply@localhost
      MOODLE_MAIL_PREFIX: "[moodle]"
      PRE_CONFIGURE_COMMANDS: |
        echo 'This is a pre-configure command'
      POST_CONFIGURE_COMMANDS: |
        echo 'This is a post-configure command'
      # 1. Turn it ON (This overrides custom.ini)
      opcache_enable: "1"
      opcache_enable_cli: "1"
      
      # 2. Scale up memory & files for Moodle + Plugins
      opcache_memory_consumption: "512"
      opcache_interned_strings_buffer: "64"
      opcache_max_accelerated_files: "60000"
      
      # 3. Code change validation behavior
      # Set to "1" if you're actively developing code. 
      # Set to "0" (as your guide suggests) for true production speed.
      opcache_validate_timestamps: "1"
      opcache_revalidate_freq: "60"
      
      # 4. Mandatory settings for Moodle
      opcache_save_comments: "1"
      opcache_enable_file_override: "1"
      
      # 5. PHP 8.4 JIT Compiler Settings
      opcache_jit: "tracing"
      opcache_jit_buffer_size: "128M"
    ports:
      - 80:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    depends_on:
      - postgres
      - redis

volumes:
  postgres: null
  moodledata: null
  moodlehtml: null
