---
services:

  redis:
    image: redis:alpine
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_DB=moodle
    volumes:
      - postgres:/var/lib/postgresql

  moodle:
    image: ruseler/alpine-moodle:4.5
    #build:
    #  context: .
    #  args:
        # 1. Set the Moodle branch to build (default: MOODLE_405_STABLE)
        # 2. Set the custom plugin repository URL (default: AdrianoRuseler/moodle405-plugins)
    #    MOODLE_BRANCH: MOODLE_405_STABLE
    #    MOODLE_PGLS: AdrianoRuseler/moodle405-plugins
    restart: unless-stopped
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      SITE_URL: http://localhost
      DB_TYPE: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: moodle
      DB_PREFIX: mdl_
      REDIS_HOST: redis
      REVERSEPROXY: false
      SSLPROXY: false
      MOODLE_EMAIL: admin@host.docker.internal
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: M@0dl3ing
      MOODLE_MAIL_NOREPLY_ADDRESS: noreply@host.docker.internal
      POST_CONFIGURE_COMMANDS: |
        echo 'Starting background Moodle cron loop...'
        sh -c 'while true; do php /var/www/html/admin/cli/cron.php; sleep 60; done' &
    ports:
      - 80:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    depends_on:
      - postgres
      - redis
volumes:
  postgres: null
  moodledata: null
  moodlehtml: null
